### ISSUE TITLE
NPM install error on a Mac OS system

### ISSUE THREAD

**Issue by emin93** [SuperiorJT/angular2-qrcode#15]
I get the following error when i try to install angular2-qrcode:

```
npm install angular2-qrcode --save

> canvas@1.6.3 install /Users/emin93/WebstormProjects/MyProject/node_modules/canvas
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

SOLINK_MODULE(target) Release/canvas-postbuild.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/emin93/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/emin93/.nvm/versions/node/v6.9.4/bin/node" "/Users/emin93/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/emin93/WebstormProjects/MyProject/node_modules/canvas
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

But when i try to use it in my app it seems to work anyway. Not sure why this error happens.

**Comment by TamiasSibiricus** [comment]
You should need to install dev libraries for cairo module native build.
Take a look [here](https://github.com/Automattic/node-canvas/wiki/Installation---OSX)

**Comment by SuperiorJT** [comment]
Ignore the error for now. Currently there is no way to declare the `--no-optional` flag in `package.json`.
