### ISSUE TITLE
create this error  with ionic 2  

### ISSUE THREAD

**Issue by abmnukmr** [SuperiorJT/angular2-qrcode#17]
build prod failed: Unexpected value 'QRCodeModule' imported by the module 'AppModule' 
[02:26:11]  ionic-app-script task: "build" 
[02:26:11]  Error: Unexpected value 'QRCodeModule' imported by the module 'AppModule' 
Error: Unexpected value 'QRCodeModule' imported by the module 'AppModule'
    at E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:14078:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:14063:46)
    at E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:12865:47
    at Array.forEach (native)
    at analyzeModules (E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:12864:17)
    at OfflineCompiler.analyzeModules (E:\ionic app\ionicc1\node_modules\@angular\compiler\bundles\compiler.umd.js:12889:18)
    at CodeGenerator.codegen (E:\ionic app\ionicc1\node_modules\@angular\compiler-cli\src\codegen.js:121:47)
    at Object.runCodegen (E:\ionic app\ionicc1\node_modules\@ionic\app-scripts\dist\aot\codegen\codegen-ng22.js:15:26)
    at Object.doCodegen (E:\ionic app\ionicc1\node_modules\@ionic\app-scripts\dist\aot\codegen.js:6:31)

**Comment by SuperiorJT** [comment]
Closing this with the 2.0.1 release.
