### ISSUE TITLE
 ionic build android --prod error in ionic 2

### ISSUE THREAD

**Issue by huigesv123** [SuperiorJT/angular2-qrcode#22]
using 2.0.1 android ionic 2.2.2 ,cordova 6.5.0

build prod failed: Metadata version mismatch for module 
            /Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/angular2-qrcode/lib/angular2-qrcode.d.ts, 
            found version 2.0.1, expected 1 
[17:11:10]  ionic-app-script task: "build" 
[17:11:10]  Error: Metadata version mismatch for module 
            /Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/angular2-qrcode/lib/angular2-qrcode.d.ts, 
            found version 2.0.1, expected 1 
Error: Metadata version mismatch for module /Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/angular2-qrcode/lib/angular2-qrcode.d.ts, found version 2.0.1, expected 1
    at StaticReflector.getModuleMetadata (/Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@angular/compiler-cli/src/static_reflector.js:500:23)
    at /Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@angular/compiler-cli/src/codegen.js:122:46
    at Array.forEach (native)
    at extractProgramSymbols (/Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@angular/compiler-cli/src/codegen.js:120:10)
    at CodeGenerator.codegen (/Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@angular/compiler-cli/src/codegen.js:57:29)
    at Object.runCodegen (/Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@ionic/app-scripts/dist/aot/codegen/codegen-ng22.js:15:26)
    at Object.doCodegen (/Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@ionic/app-scripts/dist/aot/codegen.js:6:31)
    at /Users/suboan/Desktop/ProjectFile/ionic2/vwAPP_2.0/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:41:30

**Comment by afeezaziz** [comment]
Yes, I am facing the same problem with this too as I was unable to find/get the correct version when use --prod. I can confirm that this problem persists for both Android and iOS.
