### ISSUE TITLE
ypescript: src/pages/ap/ap.module.ts, line: 4  Cannot find module 'angular2-qrcode'.

### ISSUE THREAD

**Issue by nimi96** [SuperiorJT/angular2-qrcode#35]
hy , i am building  ionic app and i am using angular2-qrcode.  everything is done right app is running perfect offline but when i deploy on ionic view for testing.  it shows Build failed error.

**Comment by nimi96** [comment]
Running with gitlab-ci-multi-runner 9.1.0 (0118d89)
  on ip-10-2-180-113 (c9648220)
Using Shell executor...
Running on ip-10-2-180-113...
Cloning repository...
Cloning into '/home/gitlab-runner/builds/c9648220/0/project-1'...
Checking out fe29cecc as master...
Skipping Git submodules setup
$ run "fetch-updates"
Running Stage fetch-updates for Job: 5352451
Checking for build process updates...
$ run "build-app"
Running Stage build-app for Job: 5352451
Parsing ionic.config.json for project settings
Project Settings:
	Name: wonka_app
	App ID: dc75289f
	Type: ionic-angular
Build script detected in package.json...
$ npm install --quiet --no-optional

> leveldown@1.5.0 install /usr/src/app/node_modules/leveldown
> prebuild --install

prebuild WARN install /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/src/app/node_modules/leveldown/build/Release/leveldown.node)
make: Entering directory '/usr/src/app/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.19/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
  CXX(target) Release/obj.target/leveldown/src/batch_async.o
  CXX(target) Release/obj.target/leveldown/src/database.o
  CXX(target) Release/obj.target/leveldown/src/database_async.o
  CXX(target) Release/obj.target/leveldown/src/iterator.o
  CXX(target) Release/obj.target/leveldown/src/iterator_async.o
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
  SOLINK_MODULE(target) Release/obj.target/leveldown.node
  COPY Release/leveldown.node
make: Leaving directory '/usr/src/app/node_modules/leveldown/build'

> node-sass@4.7.2 install /usr/src/app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-57_binding.node
Download complete
Binary saved to /usr/src/app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/gitlab-runner/.npm/node-sass/4.7.2/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/src/app/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall /usr/src/app/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/src/app/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN @techiediaries/ngx-qrcode@0.0.5 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN ngx-qrcode2@0.0.5 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN ngx-qrcode3@0.3.0 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.

added 992 packages in 62.404s
$ npm install --quiet --no-optional success
$ npm run build
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm info lifecycle wonka_app@0.0.1~prebuild: wonka_app@0.0.1
npm info lifecycle wonka_app@0.0.1~build: wonka_app@0.0.1

> wonka_app@0.0.1 build /usr/src/app
> ionic-app-scripts build

[11:14:59]  ionic-app-scripts 3.1.8 
[11:14:59]  build dev started ... 
[11:14:59]  clean started ... 
[11:14:59]  clean finished in 1 ms 
[11:14:59]  copy started ... 
[11:14:59]  deeplinks started ... 
[11:14:59]  deeplinks finished in 111 ms 
[11:14:59]  transpile started ... 
[11:15:02]  typescript: src/app/app.module.ts, line: 11 
            Cannot find module 'angular2-qrcode'. 

      L10:  import { BarcodeScanner } from '@ionic-native/barcode-scanner';
      L11:  import { QRCodeModule } from 'angular2-qrcode';
[11:15:02]  typescript: src/pages/ap/ap.module.ts, line: 4 

            Cannot find module 'angular2-qrcode'. 

       L3:  import { ApPage } from './ap';
       L4:  import { QRCodeModule } from 'angular2-qrcode';
       L5:  @NgModule({

            Cannot find module 'angular2-qrcode'. 

       L5:  import { AlertController } from 'ionic-angular';
       L6:  import {QRCodeComponent} from 'angular2-qrcode';
       L7:  //import * as Pouchdb from 'pouchdb';

            Cannot find module 'angular2-qrcode'. 
[11:15:02]  typescript: src/pages/ap/ap.ts, line: 6 
[11:15:02]  typescript: src/pages/tab1/tab1.module.ts, line: 4 

       L3:  import { Tab1Page } from './tab1';
       L4:  import { QRCodeModule } from 'angular2-qrcode';
       L5:  @NgModule({

            Cannot find module 'angular2-qrcode'. 

       L3:  import { Camera, CameraOptions } from '@ionic-native/camera';
[11:15:02]  typescript: src/pages/tab1/tab1.ts, line: 4 
       L4:  import {QRCodeComponent} from 'angular2-qrcode';
       L5:  import * as PouchDB from 'pouchdb';

[11:15:02]  ionic-app-script task: "build" 
[11:15:02]  Error: Failed to transpile program 
Error: Failed to transpile program
    at new BuildError (/usr/src/app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at Promise ()
    at transpileWorker (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/usr/src/app/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /usr/src/app/node_modules/@ionic/app-scripts/dist/build.js:109:82
    at 
npm info lifecycle wonka_app@0.0.1~build: Failed to exec build script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wonka_app@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wonka_app@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2018-03-01T11_15_02_758Z-debug.log
npm run build failed
Running after script...
$ run "clean-up"
Running Stage clean-up for Job: 5352451
ERROR: Job failed: exit status 1
